### ISSUE TITLE
some special character could not be readed.

### ISSUE THREAD

**Issue by caihebht** [cobwebch/svconnector_sql#5]
**Here  is a schede_meta with following values in my external Database (SQL):**
fotograf-5555-Rokeby Hall, Yorkshire (GB)-Frontaufnahme-qualitaet-PH0014790.jpg-0,fotograf-5555-Rokeby Hall, Yorkshire (GB)-schräge Aufnahme-qualitaet-PH0014791.jpg-0 

**But in typo3 part of the Vaule will not showing**
schede_meta => 'fotograf-5555-Rokeby Hall, Yorkshire (GB)-Frontaufnahme-qualitaet-PH0014790.
         
         H0014791.jpg-0' (166 chars)

which special character should I use?

**Comment by fsuter** [comment]
I have no idea and your text ended up formatted in a strange way. Can you repost this differently somehow?

**Comment by caihebht** [comment]
> I have no idea and your text ended up formatted in a strange way. Can you repost this differently somehow?

I found out, that was my own mistake :D
